### ISSUE TITLE
On PRNG seeding

### ISSUE THREAD

**Issue by christophe-pouzat** [vmagnin/exploring_coarrays#4]
Hi,
Thanks for these very useful examples. Just a remark on the seeding of the PRNG. instead of:
```f90
 ! Each image will have its own RNG seed:
 call rng%seed([ -1337_i8, 9812374_i8 ] + 10*this_image())
```
I would suggest something like:
```f90
call rng%seed([ -1337_i8, 9812374_i8 ])
if (this_image() /= 1) then
  do i = 2, this_image()
    call rng%jump()
  end do
end if
```
The PRNG sequences on the different images are then  guaranteed not to overlap.

Best,

Christophe

**Comment by vmagnin** [comment]
Thanks Christophe,

I will integrate your remark, not the next week but rather at the beginning of July when I have some time for looking into that project.

Best,
Vincent

**Comment by vmagnin** [comment]
Done.
